# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dental-assistant-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # build-bot:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Node.js version
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'

  #     - name: npm install, build, and test
  #       run: |
  #         cd starter/ContosoDentistryChatBot
  #         npm install
  #         npm run build --if-present
  #         npm run test --if-present

  #     - name: Zip artifact for deployment
  #       run: |
  #         cd starter/ContosoDentistryChatBot
  #         zip ../../release.zip ./* -r

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: node-app
  #         path: release.zip

  # deploy-bot:
  #   runs-on: ubuntu-latest
  #   needs: build-bot
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  #   permissions:
  #     id-token: write #This is required for requesting the JWT

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: node-app

  #     - name: Create target directory
  #       run: |
  #         mkdir -p starter/ContosoDentistryChatBot

  #     - name: Unzip artifact for deployment
  #       run: |
  #         unzip release.zip -d starter/ContosoDentistryChatBot
      
  #     - name: Login to Azure
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6AE6C65C0EE740AA87B98A5B707E3BD2 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1C8C235289554FFDBCE39C00AC9A9A4F }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48D32ACE05B441A584DE7433595099F3 }}

  #     - name: 'Deploy to Azure Web App'
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'dental-assistant-webapp'
  #         slot-name: 'Production'
  #         package: ./starter/ContosoDentistryChatBot
  
  build-scheduler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd starter/ContosoDentistryScheduler
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd starter/ContosoDentistryScheduler
          zip ../../release2.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app2
          path: release2.zip

  deploy-scheduler:
    runs-on: ubuntu-latest
    needs: build-scheduler
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app2

      - name: Create target directory
        run: |
          mkdir -p starter/ContosoDentistryScheduler

      - name: Unzip artifact for deployment
        run: |
          unzip release2.zip -d starter/ContosoDentistryScheduler
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6AE6C65C0EE740AA87B98A5B707E3BD2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1C8C235289554FFDBCE39C00AC9A9A4F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48D32ACE05B441A584DE7433595099F3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dental-scheduler-app'
          slot-name: 'Production'
          package: ./starter/ContosoDentistryScheduler